{% set name = "LbAPLocal" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPLocal-{{ version }}.tar.gz
  sha256: 2a292547f670b9267dce58cdc8e6491076246e93060a55ba92f46288ce6b6b8f

build:
  number: 0
  noarch: python
  entry_points:
    - lb-ap=LbAPLocal.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click
    - consolemd
    - lbapcommon ~=0.5.0
    - lbdiracwrappers
    - lbenv
    - python >=3.8
    - requests
    - requests-kerberos
    - setuptools

test:
  imports:
    - LbAPLocal
  commands:
    - pip check
    - lb-ap --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  summary: Tool to locally run tests for AnalysisProductions
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AidanWiederhold
    - chrisburr
