{% set name = "lbaplocal" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPLocal-{{ version }}.tar.gz
  sha256: deff92737d47ddc938d19edbbc692d322faab3ea2c7749b1e763d264a149f85c

build:
  number: 0
  noarch: python
  entry_points:
    - lb-ap=LbAPLocal.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - click
    - consolemd
    - lbapcommon >=0.0.6
    - lbdiracwrappers
    - lbenv
    - python >=3.8
    - requests
    - requests-kerberos

test:
  imports:
    - LbAPLocal
  commands:
    - pip check
    - lb-ap --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  summary: Tool to locally run tests for AnalysisProductions
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
