{% set name = "LbAPLocal" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPLocal-{{ version }}.tar.gz
  sha256: de31bd814397c95b8668bc26f2fa1ee2f727597b2531534f5d6670ca68166c73

build:
  number: 0
  noarch: python
  entry_points:
    - lb-ap=LbAPLocal.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - click
    - consolemd
    - lbapcommon ~=0.7.0
    - lbdiracwrappers
    - lbenv
    - lbprodrun ~=1.2
    - mplhep
    - python >=3.9
    - requests
    - setuptools

test:
  imports:
    - LbAPLocal
  commands:
    - pip check
    - lb-ap --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  summary: Tool to locally run tests for AnalysisProductions
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AidanWiederhold
    - chrisburr
