{% set name = "lbaplocal" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPLocal-{{ version }}.tar.gz
  sha256: d887ccbee626a206f87623702b80e1fa421867d6959e233768b30b30a5a2502d

build:
  entry_points:
    - lb-ap=LbAPLocal.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - click
    - consolemd
    - lbapcommon >=0.8.0,<0.9.dev0
    - apd >=0.4.0,<0.5.dev0
    - lbenv
    - lbdiracwrappers
    - requests
    - setuptools
    - mplhep
    - lbprodrun >=1.3,<2.dev0

test:
  imports:
    - LbAPLocal
  commands:
    - pip check
    - lb-ap --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  summary: Tool to locally run tests for AnalysisProductions
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AidanWiederhold
    - chrisburr
